export const data = [
  {
    id: 1,
    name: "Osborne",
    phone: "691-509-3056",
    description: "Effects of hunger",
    service: 1,
    payment_status: true,
    payment_method: 1,
  },
  {
    id: 2,
    name: "Calvin",
    phone: "234-188-2181",
    description: "Cataract extract status",
    service: 2,
    payment_status: false,
    payment_method: 0,
  },
  {
    id: 3,
    name: "Elianore",
    phone: "362-481-2022",
    description: "Syndactyly, multiple/NOS",
    service: 3,
    payment_status: false,
    payment_method: 0,
  },
  {
    id: 4,
    name: "Rosita",
    phone: "979-205-7119",
    description: "Candidal meningitis",
    service: 4,
    payment_status: true,
    payment_method: 1,
  },
  {
    id: 5,
    name: "Lorrie",
    phone: "163-379-0987",
    description: "Ca in situ scalp",
    service: 5,
    payment_status: true,
    payment_method: 1,
  },
  {
    id: 6,
    name: "Paxon",
    phone: "409-936-1904",
    description: "War inj:gasoline bomb",
    service: 6,
    payment_status: false,
    payment_method: 0,
  },
  {
    id: 7,
    name: "Lela",
    phone: "809-755-3899",
    description: "Amputat foot, bilat-comp",
    service: 7,
    payment_status: true,
    payment_method: 0,
  },
  {
    id: 8,
    name: "Juliet",
    phone: "760-154-8779",
    description: "Eustachian tube dis NEC",
    service: 8,
    payment_status: false,
    payment_method: 1,
  },
  {
    id: 9,
    name: "Hartley",
    phone: "652-991-8298",
    description: "Hodg nodul sclero spleen",
    service: 9,
    payment_status: false,
    payment_method: 0,
  },
  {
    id: 10,
    name: "Sharyl",
    phone: "436-131-5589",
    description: "Adv eff alcohol deter",
    service: 10,
    payment_status: false,
    payment_method: 1,
  },
  {
    id: 11,
    name: "Clio",
    phone: "547-315-5544",
    description: "Cord around neck-unspec",
    service: 11,
    payment_status: true,
    payment_method: 11,
  },
  {
    id: 12,
    name: "Virge",
    phone: "743-275-3474",
    description: "Pinta mixed lesions",
    service: 12,
    payment_status: false,
    payment_method: 12,
  },
  {
    id: 13,
    name: "Shani",
    phone: "456-905-2885",
    description: "Mgrn wo aura wo ntrc mgr",
    service: 13,
    payment_status: true,
    payment_method: 13,
  },
  {
    id: 14,
    name: "Camala",
    phone: "371-112-8341",
    description: "Mv n-traf acc NEC-mocycl",
    service: 14,
    payment_status: true,
    payment_method: 14,
  },
  {
    id: 15,
    name: "Dorian",
    phone: "971-474-8521",
    description: "Soft tissue disord NOS",
    service: 15,
    payment_status: false,
    payment_method: 15,
  },
  {
    id: 16,
    name: "Errol",
    phone: "201-551-4363",
    description: "Tk off/land-psng aircrft",
    service: 16,
    payment_status: true,
    payment_method: 16,
  },
  {
    id: 17,
    name: "Noell",
    phone: "876-439-5192",
    description: "Coccidiosis",
    service: 17,
    payment_status: true,
    payment_method: 17,
  },
  {
    id: 18,
    name: "Alta",
    phone: "112-313-8815",
    description: "React-cardiac dev/graft",
    service: 18,
    payment_status: false,
    payment_method: 18,
  },
  {
    id: 19,
    name: "Mariellen",
    phone: "672-966-5806",
    description: "Outlet dysfnc constption",
    service: 19,
    payment_status: false,
    payment_method: 19,
  },
  {
    id: 20,
    name: "Anette",
    phone: "262-849-5282",
    description: "3rd deg burn toe",
    service: 20,
    payment_status: false,
    payment_method: 20,
  },
  {
    id: 21,
    name: "Barbara-anne",
    phone: "933-815-5094",
    description: "Pyogen arthritis-forearm",
    service: 21,
    payment_status: true,
    payment_method: 21,
  },
  {
    id: 22,
    name: "Farand",
    phone: "324-260-7298",
    description: "Forearm deformity NOS",
    service: 22,
    payment_status: false,
    payment_method: 22,
  },
  {
    id: 23,
    name: "Theo",
    phone: "338-947-2857",
    description: "Complic med care NEC/NOS",
    service: 23,
    payment_status: true,
    payment_method: 23,
  },
  {
    id: 24,
    name: "Kore",
    phone: "269-742-6867",
    description: "Dissection renal artery",
    service: 24,
    payment_status: true,
    payment_method: 24,
  },
  {
    id: 25,
    name: "Gigi",
    phone: "465-349-3756",
    description: "Orbital myositis",
    service: 25,
    payment_status: false,
    payment_method: 25,
  },
  {
    id: 26,
    name: "Kalina",
    phone: "744-360-5663",
    description: "Acute nasopharyngitis",
    service: 26,
    payment_status: false,
    payment_method: 26,
  },
  {
    id: 27,
    name: "Gunter",
    phone: "604-258-1814",
    description: "Endocarditis in oth dis",
    service: 27,
    payment_status: false,
    payment_method: 27,
  },
  {
    id: 28,
    name: "Kele",
    phone: "175-645-0156",
    description: "Aftrcare path fx low leg",
    service: 28,
    payment_status: true,
    payment_method: 28,
  },
  {
    id: 29,
    name: "Celisse",
    phone: "478-419-9214",
    description: "Mult crushing injury arm",
    service: 29,
    payment_status: false,
    payment_method: 29,
  },
  {
    id: 30,
    name: "Shayla",
    phone: "115-607-4761",
    description: "Post tp lymphprolif dis",
    service: 30,
    payment_status: true,
    payment_method: 30,
  },
  {
    id: 31,
    name: "Shepperd",
    phone: "280-221-5459",
    description: "Food pois: v. parahaem",
    service: 31,
    payment_status: true,
    payment_method: 31,
  },
  {
    id: 32,
    name: "Jack",
    phone: "651-896-3478",
    description: "Spon abor w pel inf-comp",
    service: 32,
    payment_status: true,
    payment_method: 32,
  },
  {
    id: 33,
    name: "Martina",
    phone: "645-948-1262",
    description: "Malignant neo colon NEC",
    service: 33,
    payment_status: true,
    payment_method: 33,
  },
  {
    id: 34,
    name: "Suki",
    phone: "790-238-2819",
    description: "Hemorrhagic cond NEC",
    service: 34,
    payment_status: true,
    payment_method: 34,
  },
  {
    id: 35,
    name: "Jed",
    phone: "237-414-9690",
    description: "Leg varicosity w ulcer",
    service: 35,
    payment_status: true,
    payment_method: 35,
  },
  {
    id: 36,
    name: "Isidora",
    phone: "918-364-8231",
    description: "Herpetic whitlow",
    service: 36,
    payment_status: true,
    payment_method: 36,
  },
  {
    id: 37,
    name: "Stacia",
    phone: "261-135-5844",
    description: "Renal dis NOS-delivered",
    service: 37,
    payment_status: false,
    payment_method: 37,
  },
  {
    id: 38,
    name: "Nedi",
    phone: "665-385-7028",
    description: "Prim uterine inert-unsp",
    service: 38,
    payment_status: true,
    payment_method: 38,
  },
  {
    id: 39,
    name: "Abigale",
    phone: "155-505-6426",
    description: "Exfl d/t eryth 20-29 bdy",
    service: 39,
    payment_status: false,
    payment_method: 39,
  },
  {
    id: 40,
    name: "Klarika",
    phone: "219-658-0658",
    description: "Toxoplasma pneumonitis",
    service: 40,
    payment_status: true,
    payment_method: 40,
  },
  {
    id: 41,
    name: "Carey",
    phone: "537-103-7465",
    description: "Gc prostatitis, chronic",
    service: 41,
    payment_status: true,
    payment_method: 41,
  },
  {
    id: 42,
    name: "Tabbitha",
    phone: "483-953-1072",
    description: "RR coll w oth obj-employ",
    service: 42,
    payment_status: false,
    payment_method: 42,
  },
  {
    id: 43,
    name: "Murray",
    phone: "693-196-1239",
    description: "Lymphosarcoma pelvic",
    service: 43,
    payment_status: false,
    payment_method: 43,
  },
  {
    id: 44,
    name: "Reid",
    phone: "239-710-7444",
    description: "Epilep NEC w/o intr epil",
    service: 44,
    payment_status: false,
    payment_method: 44,
  },
  {
    id: 45,
    name: "Binnie",
    phone: "883-906-9777",
    description: "Hx-prostatic malignancy",
    service: 45,
    payment_status: false,
    payment_method: 45,
  },
  {
    id: 46,
    name: "Marleah",
    phone: "531-691-7242",
    description: "Del w 1 deg lacerat-del",
    service: 46,
    payment_status: true,
    payment_method: 46,
  },
  {
    id: 47,
    name: "Isis",
    phone: "321-756-8232",
    description: "Abnormal chest sounds",
    service: 47,
    payment_status: false,
    payment_method: 47,
  },
  {
    id: 48,
    name: "Jessica",
    phone: "212-816-2755",
    description: "Periph vascular dis NOS",
    service: 48,
    payment_status: false,
    payment_method: 48,
  },
  {
    id: 49,
    name: "Sascha",
    phone: "736-814-1550",
    description: "80-89% bdy brn/10-19% 3d",
    service: 49,
    payment_status: false,
    payment_method: 49,
  },
  {
    id: 50,
    name: "Bartolemo",
    phone: "398-546-3480",
    description: "Acute tonsillitis",
    service: 50,
    payment_status: true,
    payment_method: 50,
  },
];
