import girl2 from "../../public/girls-img/girl2.png";

const memberData = [
  {
    id: "01",
    img: girl2,
    name: "Suresh Ranathunga",
    birthDay: "1998-01-21",
    age: 24,
    feet: 5,
    inch: 5,
    nicNo: "983262732v",
    mobileNumber: "0764117246",
    nation: 1,
    religion: 2,
    caste: 4,
    job: "Designer & Developer",
    address: "Kolongoda Obbegoda monaragala",
    district: "Monaragala",
    maritalStatus: "None",
    monthlyIncome: 100000,
    approval: false,
  },
  {
    id: "02",
    img: girl2,
    name: "Aisha Patel",
    birthDay: "1995-05-15",
    age: "28",
    feet: 5,
    inch: 5,
    nicNo: "A1234567X",
    mobileNumber: "555-555-5555",
    nation: "Indian",
    religion: "Hindu",
    caste: "Patel",
    job: "Software Engineer",
    address: "123 Main Street, Mumbai",
    district: "Mumbai",
    maritalStatus: "Married",
    monthlyIncome: 80000,
    approval: true,
    status: true,
  },
  {
    id: "03",
    img: girl2,
    name: "Emily Johnson",
    birthDay: "1990-12-10",
    age: "32",
    feet: 5,
    inch: 5,
    nicNo: "E7890123Y",
    mobileNumber: "555-123-4567",
    nation: "American",
    religion: "Christian",
    caste: "N/A",
    job: "Teacher",
    address: "789 Elm Street, New York",
    district: "New York",
    maritalStatus: "Single",
    monthlyIncome: 55000,
    approval: true,
    status: false,
  },
  {
    id: "04",
    img: girl2,
    name: "Juan Rodriguez",
    birthDay: "1987-08-28",
    age: "36",
    feet: 5,
    inch: 5,
    nicNo: "J4567890Z",
    mobileNumber: "555-789-1234",
    nation: "Spanish",
    religion: "Catholic",
    caste: "Rodriguez",
    job: "Accountant",
    address: "456 Oak Street, Madrid",
    district: "Madrid",
    maritalStatus: "Married",
    monthlyIncome: 70000,
    approval: false,
    status: true,
  },
  {
    id: "05",
    img: girl2,
    name: "Sophie Kim",
    birthDay: "2000-03-05",
    age: "23",
    feet: 5,
    inch: 5,
    nicNo: "S5678901A",
    mobileNumber: "555-987-6543",
    nation: "Korean",
    religion: "Buddhist",
    caste: "Kim",
    job: "Graphic Designer",
    address: "321 Cherry Lane, Seoul",
    district: "Seoul",
    maritalStatus: "Single",
    monthlyIncome: 60000,
    approval: false,
    status: false,
  },
  {
    id: "06",
    img: girl2,
    name: "Mohan Singh",
    birthDay: "1983-06-20",
    age: "40",
    feet: 5,
    inch: 5,
    nicNo: "M3456789B",
    mobileNumber: "555-234-5678",
    nation: "Indian",
    religion: "Sikh",
    caste: "Singh",
    job: "Doctor",
    address: "456 Oak Lane, Delhi",
    district: "Delhi",
    maritalStatus: "Married",
    monthlyIncome: 90000,
    approval: true,
    status: false,
  },
  {
    id: "07",
    img: girl2,
    name: "Anna Smith",
    birthDay: "1992-11-15",
    age: "31",
    feet: 5,
    inch: 5,
    nicNo: "A2345678C",
    mobileNumber: "555-345-6789",
    nation: "American",
    religion: "Christian",
    caste: "N/A",
    job: "Marketing Manager",
    address: "789 Pine Street, Los Angeles",
    district: "Los Angeles",
    maritalStatus: "Single",
    monthlyIncome: 75000,
    approval: true,
    status: true,
  },
  {
    id: "08",
    img: girl2,
    name: "Carlos Gonzalez",
    birthDay: "1995-09-12",
    age: "28",
    feet: 5,
    inch: 5,
    nicNo: "C1234567D",
    mobileNumber: "555-456-7890",
    nation: "Mexican",
    religion: "Catholic",
    caste: "Gonzalez",
    job: "Engineer",
    address: "123 Oak Avenue, Mexico City",
    district: "Mexico City",
    maritalStatus: "Married",
    monthlyIncome: 85000,
    approval: false,
    status: false,
  },
  {
    id: "09",
    img: girl2,
    name: "Luisa Hernandez",
    birthDay: "1997-02-25",
    age: "26",
    feet: 5,
    inch: 5,
    nicNo: "L6789012E",
    mobileNumber: "555-567-8901",
    nation: "Mexican",
    religion: "Catholic",
    caste: "Hernandez",
    job: "Nurse",
    address: "456 Maple Street, Guadalajara",
    district: "Guadalajara",
    maritalStatus: "Single",
    monthlyIncome: 62000,
    approval: true,
    status: false,
  },
  {
    id: "10",
    img: girl2,
    name: "David Johnson",
    birthDay: "1985-07-12",
    age: "38",
    feet: 5,
    inch: 5,
    nicNo: "D8901234F",
    mobileNumber: "555-678-9012",
    nation: "American",
    religion: "Protestant",
    caste: "N/A",
    job: "Architect",
    address: "789 Cedar Street, Chicago",
    district: "Chicago",
    maritalStatus: "Married",
    monthlyIncome: 95000,
    approval: true,
    status: false,
  },
];

export default memberData;
